version: '3'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_DB_ENGINE=sqlite3
      - DJANGO_DB_NAME=db.sqlite3
    command: >
      bash -c "python bookproject/manage.py makemigrations &&
               python bookproject/manage.py migrate &&
               python bookproject/manage.py seed --number 3 &&
               python bookproject/manage.py runserver 0.0.0.0:8000"

    depends_on:
      - redis

  redis:
    image: "redis:alpine"
