# Generated by Django 4.2.6 on 2024-03-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_lexile_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
