# Generated by Django 4.2.6 on 2024-03-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0002_userprofile_level_userprofile_xp'),
        ('profileapp', '0002_userprofile_total_lexile_score'),
    ]

    operations = [
    ]
