# Generated by Django 4.2.6 on 2024-03-14 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0004_library'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Library',
        ),
    ]
