# Generated by Django 4.2.6 on 2024-03-15 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_remove_book_category_remove_book_difficulty_and_more'),
        ('profileapp', '0005_delete_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.ManyToManyField(blank=True, related_name='libraries', to='bookapp.book')),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='library', to='profileapp.userprofile')),
            ],
        ),
    ]
