# Generated by Django 4.2.6 on 2024-03-16 20:39


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_merge_20240313_1717'),
        ('profileapp', '0006_library'),
    ]

    operations = [
    ]
