# Generated by Django 4.2.6 on 2024-03-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0007_merge_0003_merge_20240313_1717_0006_library'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='xp',
            new_name='user_xp_total',
        ),
    ]
