# Generated by Django 4.2.6 on 2024-03-16 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_rename_xp_userprofile_user_xp_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_lexile_score',
        ),
    ]
