# Generated by Django 4.2.6 on 2024-03-16 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_alter_book_isbn'),
        ('profileapp', '0009_remove_userprofile_total_lexile_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pages_read', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='bookapp.book')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_books', to='profileapp.userprofile')),
            ],
            options={
                'unique_together': {('user_profile', 'book')},
            },
        ),
    ]
