# Generated by Django 4.2.6 on 2024-03-17 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_userbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbook',
            name='xp_earned',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
