# Generated by Django 4.2.6 on 2024-03-17 15:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0012_alter_userbook_pages_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='XPUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_earned', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_updates', to='profileapp.userprofile')),
            ],
        ),
    ]
