# Generated by Django 4.2.6 on 2024-03-17 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0013_xpupdatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='pages_read',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
