# Generated by Django 4.2.6 on 2024-03-17 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0014_alter_userbook_pages_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='progress_percentage_next_level',
            field=models.PositiveIntegerField(default=1000, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
