# Generated by Django 4.2.6 on 2024-03-19 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0016_alter_book_isbn'),
        ('profileapp', '0015_userprofile_progress_percentage_next_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_book', to='bookapp.book'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_book_profile', to='profileapp.userprofile'),
        ),
        migrations.DeleteModel(
            name='Library',
        ),
    ]
