# Generated by Django 4.2.8 on 2024-04-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profileapp", "0024_remove_userprofile_books_read"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="books_read",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
