# Generated by Django 4.2.6 on 2024-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0025_userprofile_books_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='session_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
