# Generated by Django 4.2.6 on 2024-05-13 18:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0027_remove_userprofile_session_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_pages_read',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
