# Generated by Django 4.2.6 on 2024-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.PositiveBigIntegerField(default=0, help_text='ISBN number'),
        ),
        migrations.AddField(
            model_name='book',
            name='lexile_xp',
            field=models.PositiveIntegerField(default=0, help_text='Lexile Measure'),
        ),
    ]
