# Generated by Django 4.2.6 on 2024-03-13 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_book_isbn_book_lexile_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='lexile_xp',
            field=models.PositiveIntegerField(default=0, help_text='XP from lexile'),
        ),
    ]
