# Generated by Django 4.2.6 on 2024-03-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0004_book_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
