# Generated by Django 4.2.6 on 2024-03-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_rename_categories_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_books_id',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
