# Generated by Django 4.2.6 on 2024-03-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0007_remove_book_google_books_id_book_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.RemoveField(
            model_name='book',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='book',
            name='lexile_xp',
        ),
        migrations.AddField(
            model_name='book',
            name='xp',
            field=models.IntegerField(default=0, help_text='XP points'),
        ),
    ]
