# Generated by Django 4.2.6 on 2024-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0008_remove_book_category_remove_book_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(default='static/img/cover_art/default_image.svg', upload_to='static/img/cover_art'),
        ),
    ]
