# Generated by Django 4.2.6 on 2024-03-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0009_book_cover_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(default='static/img/cover_art/default_image.svg', upload_to=''),
        ),
    ]
