# Generated by Django 4.2.6 on 2024-03-16 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0010_alter_book_cover_art'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='xp',
            new_name='book_total_xp',
        ),
    ]
