# Generated by Django 4.2.6 on 2024-03-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0011_rename_xp_book_book_total_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_total_xp',
            field=models.PositiveBigIntegerField(default=0, help_text='XP points'),
        ),
    ]
