# Generated by Django 4.2.6 on 2024-03-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0012_alter_book_book_total_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(default='General', max_length=255),
        ),
    ]
